################## Notes for Generating Wheels Manually ##################
### While you creating wheels manually using bdist_wheel, you create 
### <<structured_predictions-0.1.2-cp39-cp39-linux_x86_64.whl>> on linux
### but pypi needs linux wheels with manylinux format. To generate PyPi compatible
### wheels, you need to used cibuildwheel.

name: Generating Wheels

on: 
  push:
    # To ignore main branch
    branches-ignore:
      - "main"
#    branches: [ main ]
  schedule:
    - cron: '0 0 1 * *'
# pull_request:
#    branches:
#      - '*'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest]
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11'] # Gives error for Python 3.12
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and compile
        run: make dist 
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl


